create table auth.cabinet
(
    id integer primary key generated by default as identity,
    status_id integer not null,
    title text not null,
    description text,
    date_create timestamp(6) with time zone not null,
    date_delete timestamp(6) with time zone,

    foreign key (status_id) references auth.cabinet_status(id)
);