create table auth.refresh_token
(
    id integer primary key generated by default as identity,
    user_id integer not null,
    token text not null,
    expires timestamp(6) with time zone not null,
    created timestamp(6) with time zone not null,
    created_by_ip text not null,

    revoked timestamp(6) with time zone,
    revoked_by_ip text,

    replaced_by_token text,
    reason_revoked text,

	foreign key (user_id) references auth.user(id)
);