create table auth.user
(
    id integer primary key generated by default as identity,
    status_id integer not null,
    cabinet_id integer not null,
    username text not null unique,
    email text not null unique,
    photo text,
    password_hash text not null,

    date_create timestamp(6) with time zone not null,
    date_delete timestamp(6) with time zone,
    date_activation timestamp(6) with time zone,
    date_blocked timestamp(6) with time zone,
    date_unblocked timestamp(6) with time zone,
    reason_blocked text,

	foreign key (status_id) references auth.user_status(id),
    foreign key (cabinet_id) references auth.cabinet(id)
);