create table hr.skill
(
    id integer primary key generated by default as identity,
	cabinet_id integer,
	title text not null,
	test_module_link text not null,

	unique(cabinet_id, title),
	foreign key (cabinet_id) references hr.cabinet (id) on delete cascade
);