create table test.anonymous_user
(
    id integer primary key generated by default as identity,
    test_link_response_id integer not null,
    first_name text not null,
    middle_name text not null,
    last_name text not null,
    email text not null,

    foreign key (test_link_response_id) references test.test_link_response(id) on delete cascade
);