create table test.test
(
    id integer primary key generated by default as identity,
	hr_id integer not null,
	title text,
	description text,
	test_template_link text not null,

	foreign key (hr_id) references test.user(id) on delete cascade
);