create table test.test_link_response
(
    id integer primary key generated by default as identity,
    test_link_id integer not null,
    status_id integer not null,
    number_attempt integer not null,
    user_id integer,
	date_create timestamp(6) with time zone not null,
    test_generated_link text,
	
	foreign key (test_link_id) references test.test_link(id) on delete cascade,
	foreign key (status_id) references test.test_link_response_status(id),
    foreign key (user_id) references test.user(id) on delete cascade
);