create table test.test_link
(
    id integer primary key generated by default as identity,
    test_id integer not null,
    status_id integer not null,
	type_id integer not null,
    user_id integer,
    group_id integer,
    limit_candidate_count integer,
    limit_attempt integer not null,
    candidate_count integer not null,
    title text not null,
	link text not null,
	date_create timestamp(6) with time zone not null,
    date_expired timestamp(6) with time zone not null,
    date_closed timestamp(6) with time zone,
    
	
	foreign key (test_id) references test.test(id) on delete cascade,
	foreign key (status_id) references test.test_link_status(id),
    foreign key (type_id) references test.test_link_type(id),
    foreign key (user_id) references test.user(id) on delete cascade,
    foreign key (group_id) references test.group(id) on delete cascade
);