create table assistant.document
(
    id integer primary key generated by default as identity,
    type_id integer not null,
    cabinet_id integer not null,
    title text not null,

    elasticsearch_index text not null,
    foreign key (type_id) references assistant.document_type(id),

    unique(cabinet_id, title)
);